config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "events#index"

  resources :events do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event

  belongs_to :user, optional: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user, optional: true
  
  def self.search(search)
    where("title ILIKE ? OR location ILIKE ? OR description ILIKE ? OR posted_by ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%","%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    @comment = Comment.new
  end

  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(comment_params)

    redirect_to event_path(@event)
  end

  def edit
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to event_path(@event)
  end


  private
  def comment_params
    params.require(:comment).permit(:comment_by, :content).merge(user: current_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    if params[:search]
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      @events = Event.all.order("created_at DESC")
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.create!(event_params)
    redirect_to event_path(@event)
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.user == current_user
      @event.destroy
    else
      flash[:alert] = "Only the author of this post can delete it"
    end
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:title, :posted_by, :location, :level, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/comments/edit.html.erb
<div class="titles">
  <h2> Edit Comment </h2>
</div>

<div class="form">
<%= form_for  [@event, @comment] do |f| %>
  <%= f.label :comment_by, "By:"  %>
  <%= f.text_field :comment_by %>
<br>
<br>
  <%= f.label :content, "Comment:" %>
  <%= f.text_area :content %>
<br>
<br>
<br>
<%= f.submit "Update", :class =>"button_style"  %>
  <% end %>
<br>
  <%= form_for [@event, @comment], method: :delete do |f| %>
  <% f.submit "Delete", :class =>"button_style"%>
  <% end %>

app/views/comments/new.html.erb
<div class="titles">
<h2> New Comment </h2>
</div>
<div class="form">
<%= form_for  [@event, @comment] do |f| %>
  <%= f.label :comment_by, "By:" %>
  <%= f.text_field :comment_by %>
<br>
<br>
  <%= f.label :content, "Comment:" %>
  <%= f.text_area :content %>
<br>
<br>
<br>
<br>
<br>
<%= f.submit "Create", :class =>"button_style" %>
<% end %>

app/views/events/edit.html.erb
<div class="eventlinks">
  <h4><%= link_to "< Back to Event", event_path %></h4>
</div>

<div class="titles">
  <h3> Edit: <%= @event.title %></h3>
</div>
<div class="form">
<%= form_for  @event do |f| %>

  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
<br>
<br>
  <%= f.label :posted_by, "By:" %>
  <%= f.text_field :posted_by %>
<br>
<br>
  <%= f.label :location, "Where:" %>
  <%= f.text_field :location %>
<br>
<br>
<%= f.label :level, "Level:" %>
<%= f.select :level, options_for_select((1..7).step(0.5)) %>
<br>
<br>
    <%= f.label :description, "Description:" %>
    <%= f.text_area :description %>
<br>
<br>
<br>
<br>

<%= f.submit "Update", :class =>"button_style"%>
  <% end %>

<br>
<br>
  <%= form_for @event, url: event_path, method: :delete do |f| %>
  <% f.submit "Delete", :class =>"button_style"%>
  <% end %>

app/views/events/index.html.erb
<%= form_tag(events_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search Events" %>
<%= submit_tag "Search", :location => nil %>
<% end %>

<div class="titles">
  <h2>All Events </h2>
</div>

<div class="eventlinks">
  <%= link_to "Create New Event", new_event_path %>
</div>

<% if @events.blank? %>
  <h4>There are no events containing the term <%= params[:search] %>.</h4>
<% end %>

<ul>
  <% @events.each do |event| %>
<div class="events">
  <h3><%= link_to event.title, event_path(event) %> </h3>
  <div class="firstline">
    <b>Posted by: </b><%= event.posted_by %>
      | <h5><%= event.created_at.strftime("%m-%d-%Y") %> at <%= event.created_at.strftime("%I:%M %p") %></h5></div><br>
      <b>  Where: </b><%= event.location %><br><br>
      <b> Level: </b> <%= event.level %> <br>
</div>
<br>
  <% end %>
</ul>

app/views/events/new.html.erb
<div class="eventlinks">
  <h4><%= link_to "< Back to All Events", events_path %></h4>
</div>

<div class="titles">
  <h2> Create New Event</h2>
</div>

<div class="form">
<%= form_for  @event do |f| %>
  <%= f.label :title, "Title:" %>
  <%= f.text_field :title %>
<br>
<br>
  <%= f.label :posted_by, "By:" %>
  <%= f.text_field :posted_by %>
<br>
<br>
  <%= f.label :location, "Where:" %>
  <%= f.text_field :location %>
<br>
<br>
  <%= f.label :level, "Level:" %>
  <%= f.select :level, options_for_select((1..7).step(0.5)) %>
<br>
<br>
  <%= f.label :description, "Description:" %>
  <%= f.text_area :description %>
<br>
<br>
<br>
<br>

<%= f.submit "Create", :class =>"button_style"%>
  <% end %>

app/views/events/show.html.erb
<div class="eventlinks">
  <h4><%= link_to "< Back to All Events", events_path %></h4>
</div>
<br>

<div class="titles">
  <h2><%= @event.title %></h2>
</div>

<div class="eventlinks">
  <% if @event.user == current_user %>
  <h4><%= link_to"Edit Event", edit_event_path %></h4>
  <% end %>
</div>

<div class="postcontent">
 <div class="firstline"> <b>Posted by: </b><%= @event.posted_by %> | <h5><%= @event.created_at.strftime("%m-%d-%Y") %> at <%= @event.created_at.strftime("%I:%M %p") %></h5></div><br>
  <b>Where:</b> <%= @event.location %><br><br>
  <b>Level:</b> <%= @event.level %> <br><br>
    <p><%= @event.description %></p>
  <br>
</div>
<div class="wholecommentsection">
<div class="postcommentlink">
  <h4> <%= link_to "Post a comment", new_event_comment_path(@event) %> <h4>
</div>

<div class="comment">
  <% @event.comments.each do |comment| %>
  <h6> Posted by <%= comment.comment_by %> <%= comment.created_at.strftime("%m-%d-%Y %I:%M %p") %></h6>
  <p><%= comment.content %></p>
  <div class="eventlinks">
     <% if (comment.user == current_user) && current_user %>
      <%= link_to "Edit", edit_event_comment_path(@event, comment) %>
    <% end %>
  </div>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tennis Matcher</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-154667903', 'auto');
    ga('send', 'pageview');
  </script>
</head>

<body>
  <header>
    <nav>
      <div class="eventlinks">
        <h1><%= link_to image_tag('tennis_ball.png', size: "20x20") + " Tennis Matcher " + image_tag('tennis_ball.png', size: "20x20"), events_path %> </h1>
      </div>
    </nav>
  </header>
  <br>
  <div class="eventlinks">
    <% if !current_user %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Log in", new_user_session_path %>
    <% else %>
    <b><%= current_user.email %> | </b>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>
  </div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <!-- <%= form_tag(events_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Events" %>
  <%= submit_tag "Search", :location => nil %>
  <% end %> -->
  <%= yield %>
</body>
</html>